[tools]
wally = 	{source = "UpliftGames/wally", 		version = "0.3.1" }
wally-package-types = {source = "JohnnyMorganz/wally-package-types", version = "1.2.0"}
selene = {source = "kampfkarren/selene", version = "0.25.0"}
rojo = {source = "rojo-rbx/rojo", 	version = "7.4.0" }
luau-lsp = {source="JohnnyMorganz/luau-lsp", version="1.27.0"}
run-in-roblox = { source = "rojo-rbx/run-in-roblox", version = "0.3.0" }
stylua = {source = "JohnnyMorganz/StyLua", version = "0.19.1"}
wally-update = {source = "nightcycle/wally-update", version = "0.1.2"}
file-to-luau = {source="nightcycle/file-to-luau", version="1.0.0"}
