[package]
name = "nightcycle/package"
description = "A package!"
version = "0.1.0"
authors = ["CJ Oyer <coyer@nightcycle.us>"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["Packages", ".vscode"]

[dependencies]
Draw = "nightcycle/draw@1.0.6"
Maid = "nightcycle/maid@1.1.4"
ServiceProxy = "nightcycle/service-proxy@1.0.0"
Signal = "nightcycle/signal@1.0.2"
Spring = "nightcycle/spring@1.0.0"
TableUtil = "nightcycle/table-util@2.0.0"
HashUtil = "boatbomber/hashlib@1.0.0"
Queue = "nightcycle/queue@2.3.0"
