name: Validate Commit

on:
  push:

jobs:

  validate:
    runs-on: windows-latest

    strategy:
      matrix:
        scene: [main]
        include:
          - name: main
    steps:
      # Checkout your Git repo
      - uses: actions/checkout@v2

      # Install foreman and all foreman tools
      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      # Install wally packages
      - name: update wally packages
        run: wally-update patch

      - name: install wally packages
        run: wally install

      - name: generate sourcemap
        run: rojo sourcemap dev.project.json --output sourcemap.json

      - name: export wally package types
        run: wally-package-types --sourcemap sourcemap.json Packages

      - name: Install testing files
        shell: bash
        run: |
          # type definitions
          if [ ! -d "types" ]; then
            mkdir "types"
          fi
          curl -L "https://gist.github.com/nightcycle/50ca8f42147077b8f584b503030c8500/raw" > "types/testEZ.d.lua"
          curl -L "https://gist.github.com/nightcycle/ae7ea3376337512772d1d2b314ef467b/raw" > "types/remodel.d.lua"
          curl -L "https://raw.githubusercontent.com/JohnnyMorganz/luau-lsp/main/scripts/globalTypes.d.lua" > "types/globalTypes.d.lua"

          # lint definitions
          if [ ! -d "lints" ]; then
            mkdir "lints"
          fi
          curl -L "https://gist.github.com/nightcycle/a57e04de443dfa89bd08c8eb001b03c6/raw" > "lints/lua51.yml"
          curl -L "https://gist.github.com/nightcycle/93c4b9af5bbf4ed09f39aa908dffccd0/raw" > "lints/luau.yml"

      # apply code styling
      - name: style src scripts
        run: stylua src

      - name: generate sourcemap
        run: rojo sourcemap dev.project.json --output sourcemap.json

      # Test validity
      - name: typecheck src files
        run: luau-lsp analyze --sourcemap="sourcemap.json" --ignore="Packages/**" --ignore="src/Server/NPC/Animate.server.lua" --ignore="**/Packages/**" --ignore="*.spec.luau" --ignore="out/**" --flag:LuauTypeInferIterationLimit=0 --flag:LuauCheckRecursionLimit=0 --flag:LuauTypeInferRecursionLimit=0 --flag:LuauTarjanChildLimit=0 --flag:LuauTypeInferTypePackLoopLimit=0 --flag:LuauVisitRecursionLimit=0 --definitions=types/globalTypes.d.lua --flag:LuauParseDeclareClassIndexer=true src

      - name: lint src files
        run: selene src
